# Generated by Django 3.0.3 on 2020-05-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('1', 'Phd'), ('2', 'Mtech/MA/MSc/MCom/MBA'), ('3', 'BE/Btech/BA/BSc/BCom'), ('4', 'High School')], max_length=1),
        ),
    ]
