# Generated by Django 3.0.3 on 2020-05-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200504_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='passing_year',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectorjob',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectorjob',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
